### ISSUE TITLE
xlrd 2.0 removed xlsx

### ISSUE THREAD

**Issue by markwright** [ozsolarwind/siren#10]
xlrd 2.0 removed xlsx:

https://github.com/python-excel/xlrd/commit/2f015b7d4bb065e33b6c476a0f303d3a687e6271#comments

With xlrd 2.0.1 running siren-makeweatherfiles fails:

```
`% makeweatherfiles --help
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/makeweatherfiles", line 33, in <module>
    from credits import fileVersion
  File "/usr/lib/python3.10/site-packages/credits.py", line 31, in <module>
    import editini
  File "/usr/lib/python3.10/site-packages/editini.py", line 29, in <module>
    from displaytable import Table
  File "/usr/lib/python3.10/site-packages/displaytable.py", line 27, in <module>
    import displayobject
  File "/usr/lib/python3.10/site-packages/displayobject.py", line 27, in <module>
    from turbine import Turbine
  File "/usr/lib/python3.10/site-packages/turbine.py", line 30, in <module>
    from senutils import getParents, getUser
  File "/usr/lib/python3.10/site-packages/senutils.py", line 35, in <module>
    xlrd.xlsx.ensure_elementtree_imported(False, None)
AttributeError: module 'xlrd' has no attribute 'xlsx'
 %
```

I patched my local copy of senutils.py to avoid the problem:

```
--- siren-16e0a796f9c2c9201f61d865c672f9402a21afe1-orig/senutils.py     2023-02-28 20:56:29.000000000 +1100
+++ siren-16e0a796f9c2c9201f61d865c672f9402a21afe1/senutils.py  2023-03-19 21:00:11.553010251 +1100
@@ -31,10 +31,6 @@
 import sys
 from PyQt5 import QtCore, QtWidgets
 import xlrd
-if sys.version_info[1] >= 9: # python 3.9 onwards
-    xlrd.xlsx.ensure_elementtree_imported(False, None)
-    xlrd.xlsx.Element_has_iter = True
-
 
 class ClickableQLabel(QtWidgets.QLabel):
     clicked = QtCore.pyqtSignal()
```

**Comment by ozsolarwind** [comment]
Thanks Mark. Sorry for the slow response. 

I suspect those statements are no longer needed at all. I created the Workbook class (in senutils) to no longer use xlrd to read xlsx files. I just need to check that there are no "hangovers" anywhere else. I'lll leave this comment open ntil I've done more cheking (including changing my version of xlrd).

**Comment by ozsolarwind** [comment]
I've changed the code to only execute these two statements if xlrd version <= '1.x.x' and Python >= 3.9
